Repository kiwigrid/k8s-sidecar, pull requests merged in 2023-07, with the labels that each got.

#294 fix test for execute permission of script file
  src/helpers.py
Labels: bug

#293 build(deps): Bump python from 3.11.3-alpine3.16 to 3.11.4-alpine3.18
  Dockerfile
Labels: dependencies, docker

#274 Add support for file-based configuration of logging
  .github/workflows/build_and_test.yaml
  README.md
  examples/example.yaml
  examples/example_logconfig.yaml
  src/logger.py
  src/sidecar.py
  test/resources/sidecar.yaml
Labels: enhancement
